[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/tools/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 