[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirection pour le routage SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 